### ISSUE TITLE
Xcode 13.1 + iPhone12 iOS16 + iOS 16 真机包，报错Failed to prepare device for development.

### ISSUE THREAD

**Issue by LEggcookies** [ilobos/DeviceSupport#2]
重启手机重启电脑没有用，查看 16 真机包里的文件，修改时间 5.28。

**Comment by ilobos** [comment]
来晚了，我下载的是Xcode 14 beta，里面的16.0的创建时间确实是2022年5月28日 星期六 22:02；
我猜想这个大版本的更新，可能不只是缺少一个镜像文件，大概率还会需要其他SDK，所以建议下载最新的Xcode 14 beta，https://developer.apple.com/download/applications/ ；
另外，该版本的Xcode要求macOS 12.4或更高版本；请理性升级，避免不必要的麻烦。
